'use client'
import {useEffect,useMemo,useState} from 'react'
import AuthGate from '@/components/AuthGate'
import {supabase} from '@/lib/supabase'
type F={id:string,name:string,category:string,portion_label:string,portion_grams:number,kcal_per_portion:number}
const TARGET=2200
export default function Page(){
 const[foods,setFoods]=useState<F[]>([]),[meals,setMeals]=useState<any[]>([]),[mode,setMode]=useState('catalogo'),[q,setQ]=useState(''),[fid,setFid]=useState(''),[qty,setQty]=useState('1'),[meal,setMeal]=useState('Comida'),[pname,setPname]=useState(''),[pkcal,setPkcal]=useState(''),[fraction,setFraction]=useState('1'),[rname,setRname]=useState(''),[rkcal,setRkcal]=useState(''),[msg,setMsg]=useState('')
 async function load(){const d=new Date();d.setHours(0,0,0,0);const[a,b]=await Promise.all([supabase.from('food_reference').select('*').order('name').limit(1200),supabase.from('meals').select('*').gte('eaten_at',d.toISOString()).order('eaten_at',{ascending:false})]);setFoods((a.data||[]) as F[]);setMeals(b.data||[])}
 useEffect(()=>{load()},[])
 const matches=useMemo(()=>{const s=q.toLowerCase().trim();return (s?foods.filter(f=>(f.name+' '+f.category+' '+f.portion_label).toLowerCase().includes(s)):foods).slice(0,100)},[q,foods])
 const f=foods.find(x=>x.id===fid), catK=f?Number(f.kcal_per_portion)*(Number(qty)||0):0, labK=(Number(pkcal)||0)*(Number(fraction)||0), total=meals.reduce((a,x)=>a+Number(x.calories||0),0)
 async function add(p:any){const{error}=await supabase.from('meals').insert(p);setMsg(error?error.message:'✓ Registro guardado');if(!error){setQ('');setFid('');setQty('1');setPname('');setPkcal('');setFraction('1');setRname('');setRkcal('');load()}}
 async function saveCat(){if(!f||+qty<=0)return setMsg('Selecciona alimento y cantidad.');add({description:f.name,meal_type:meal,entry_mode:'catalogo',portion_label:f.portion_label,quantity:+qty,grams:Number(f.portion_grams)*+qty,calories:catK})}
 async function saveLabel(){if(!pname||+pkcal<=0)return setMsg('Captura producto y kcal de la bolsa.');add({description:pname,meal_type:meal,entry_mode:'etiqueta',portion_label:'Etiqueta',quantity:+fraction,grams:null,calories:labK})}
 async function saveFast(){if(!rname||+rkcal<=0)return setMsg('Captura descripción y calorías.');add({description:rname,meal_type:meal,entry_mode:'rapido',portion_label:'Registro rápido',quantity:1,grams:null,calories:+rkcal})}
 async function del(id:string){if(confirm('¿Eliminar este registro?')){await supabase.from('meals').delete().eq('id',id);load()}}
 return <AuthGate><h1>🍎 Alimentación</h1>
 <div className="grid"><div className="card"><span className="muted">Consumidas hoy</span><div className="kpi">{Math.round(total)} kcal</div></div><div className="card"><span className="muted">Meta diaria</span><div className="kpi">{TARGET} kcal</div></div><div className="card"><span className="muted">Balance</span><div className="kpi">{Math.abs(Math.round(TARGET-total))} kcal</div><span className="muted">{total<=TARGET?'restantes':'sobre la meta'}</span></div></div>
 <div className="card section"><h3>Registrar comida</h3><div className="quick"><button className="btn" onClick={()=>setMode('catalogo')}>🔎 Catálogo</button><button className="btn secondary" onClick={()=>setMode('etiqueta')}>🏷️ Etiqueta</button><button className="btn secondary" onClick={()=>setMode('rapido')}>⚡ Rápido</button></div>
 <div className="form-row"><select className="input" value={meal} onChange={e=>setMeal(e.target.value)}><option>Desayuno</option><option>Comida</option><option>Cena</option><option>Snack</option></select></div>
 {mode==='catalogo'&&<><p className="muted">Busca arroz, taco, tortilla, pollo, fruta… Los valores son estimados.</p><div className="form-row"><input className="input" value={q} onChange={e=>{setQ(e.target.value);setFid('')}} placeholder="Buscar alimento…"/></div><div className="form-row"><select className="input" value={fid} onChange={e=>setFid(e.target.value)}><option value="">Selecciona porción</option>{matches.map(x=><option key={x.id} value={x.id}>{x.name} · {x.portion_label} · ≈{Math.round(Number(x.kcal_per_portion))} kcal</option>)}</select><input className="input" type="number" min=".1" step=".5" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Cantidad"/><div className="preview">≈ {Math.round(catK)} kcal</div><button className="btn" onClick={saveCat}>Registrar</button></div></>}
 {mode==='etiqueta'&&<><p className="muted">Ejemplo: la bolsa indica 240 kcal; si comes media bolsa, selecciona 50%.</p><div className="form-row"><input className="input" value={pname} onChange={e=>setPname(e.target.value)} placeholder="Producto / presentación"/><input className="input" type="number" value={pkcal} onChange={e=>setPkcal(e.target.value)} placeholder="kcal de toda la bolsa"/><select className="input" value={fraction} onChange={e=>setFraction(e.target.value)}><option value="1">100%</option><option value=".75">75%</option><option value=".5">50%</option><option value=".25">25%</option></select><div className="preview">{Math.round(labK)} kcal</div><button className="btn" onClick={saveLabel}>Registrar</button></div></>}
 {mode==='rapido'&&<><p className="muted">Para comidas donde ya conoces las calorías aproximadas.</p><div className="form-row"><input className="input" value={rname} onChange={e=>setRname(e.target.value)} placeholder="Ej. 3 tacos de puesto"/><input className="input" type="number" value={rkcal} onChange={e=>setRkcal(e.target.value)} placeholder="Calorías"/><button className="btn" onClick={saveFast}>Registrar</button></div></>}{msg&&<p className="status">{msg}</p>}</div>
 <div className="card section"><h3>Comidas de hoy</h3><div className="table-wrap"><table><thead><tr><th>Hora</th><th>Tipo</th><th>Alimento</th><th>Porción</th><th>Calorías</th><th></th></tr></thead><tbody>{meals.length===0?<tr><td colSpan={6}>Sin registros hoy.</td></tr>:meals.map(x=><tr key={x.id}><td>{new Date(x.eaten_at).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}</td><td>{x.meal_type||'Comida'}</td><td>{x.description||'Alimento'}</td><td>{x.quantity||1} × {x.portion_label||((x.grams??'—')+' g')}</td><td><b>{Math.round(Number(x.calories))} kcal</b></td><td><button className="btn secondary" onClick={()=>del(x.id)}>Eliminar</button></td></tr>)}</tbody></table></div></div></AuthGate>
}