'use client'
import {useEffect,useMemo,useState} from 'react'
import AuthGate from '@/components/AuthGate'
import {supabase} from '@/lib/supabase'
const money=(n:number)=>Number(n||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'})
const fmt=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short'})
const PLAN:any[]=[['2026-09-30',8,'Cuestas'],['2026-10-01',6,'Suave'],['2026-10-02',0,'Descanso'],['2026-10-03',16,'Tirada larga'],['2026-10-04',5,'Recuperación'],['2026-10-05',0,'Descanso'],['2026-10-06',8,'Suave'],['2026-10-07',10,'Progresivo'],['2026-10-08',7,'Suave'],['2026-10-09',0,'Descanso'],['2026-10-10',18,'Trail largo'],['2026-10-11',5,'Recuperación'],['2026-10-12',0,'Descanso'],['2026-10-13',8,'Suave'],['2026-10-14',10,'Cuestas'],['2026-10-15',7,'Suave'],['2026-10-16',0,'Descanso'],['2026-10-17',21,'Trail largo'],['2026-10-18',5,'Recuperación'],['2026-10-19',0,'Descanso'],['2026-10-20',8,'Suave'],['2026-10-21',10,'Ritmo controlado'],['2026-10-22',7,'Suave'],['2026-10-23',0,'Descanso'],['2026-10-24',24,'Trail largo'],['2026-10-25',5,'Recuperación'],['2026-10-26',0,'Descanso'],['2026-10-27',7,'Suave'],['2026-10-28',8,'Cuestas suaves'],['2026-10-29',6,'Suave'],['2026-10-30',0,'Descanso'],['2026-10-31',16,'Trail controlado'],['2026-11-01',5,'Recuperación'],['2026-11-02',0,'Descanso'],['2026-11-03',6,'Suave'],['2026-11-04',5,'Suave + aceleraciones'],['2026-11-05',4,'Muy suave'],['2026-11-06',0,'Descanso'],['2026-11-07',30,'CARRERA']]
export default function Page(){
 const[events,setEvents]=useState<any[]>([]),[cards,setCards]=useState<any[]>([]),[title,setTitle]=useState(''),[date,setDate]=useState(''),[notes,setNotes]=useState(''),[msg,setMsg]=useState('')
 async function load(){const[e,c]=await Promise.all([supabase.from('agenda_events').select('*').order('event_date'),supabase.from('credit_cards').select('*')]);setEvents(e.data||[]);setCards(c.data||[])}
 useEffect(()=>{load()},[])
 async function add(){if(!title.trim()||!date)return setMsg('Escribe un evento y una fecha.');const{error}=await supabase.from('agenda_events').insert({title:title.trim(),event_date:date,notes});if(error)return setMsg(error.message);setTitle('');setDate('');setNotes('');setMsg('✓ Evento guardado');load()}
 async function remove(id:string){if(!confirm('¿Eliminar este evento?'))return;await supabase.from('agenda_events').delete().eq('id',id);load()}
 const today=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);return d},[]), horizon=useMemo(()=>{const d=new Date(today);d.setDate(d.getDate()+45);return d},[today])
 const auto=useMemo(()=>{const out:any[]=[];cards.forEach(c=>{if(c.due_date)out.push({id:'card-'+c.id,date:String(c.due_date).slice(0,10),title:`Pago ${c.name}`,detail:money(c.no_interest_payment||0),kind:'Pago'})});PLAN.forEach(p=>{const d=new Date(p[0]+'T12:00:00');if(d>=today&&d<=horizon)out.push({id:'run-'+p[0],date:p[0],title:p[1]?`Running · ${p[1]} km`:'Running · Descanso',detail:p[2],kind:'Running'})});return out},[cards,today,horizon])
 const all=[...auto,...events.map(e=>({id:e.id,date:String(e.event_date).slice(0,10),title:e.title,detail:e.notes||'',kind:'Personal',manual:true}))].sort((a,b)=>a.date.localeCompare(b.date))
 return <AuthGate><div className="dash-head"><div><h1>📅 Agenda</h1><p className="muted">Pagos y running aparecen automáticamente. Agrega aquí tus eventos personales.</p></div></div>
 <div className="card section"><h3>＋ Nuevo evento</h3><div className="form-row"><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Evento"/><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/><input className="input" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Nota opcional"/><button className="btn" onClick={add}>Guardar</button></div>{msg&&<p className="status">{msg}</p>}</div>
 <div className="card section"><div className="section-head"><h3>Próximos eventos</h3><span className="pill">45 días</span></div><div className="agenda-list">{all.filter(x=>new Date(x.date+'T12:00:00')>=today).map(x=><div className="agenda-item" key={x.id}><div className="agenda-date">{fmt(x.date)}</div><div className="agenda-main"><b>{x.title}</b><small>{x.detail}</small></div><span className="pill">{x.kind}</span>{x.manual&&<button className="icon-btn" onClick={()=>remove(x.id)}>🗑️</button>}</div>)}</div></div></AuthGate>
}
